In [1]:
#Linear Algebra with Python

import numpy as np



In [16]:
#Vectors

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

v_add = (v1-v2)
v_sub = (v1+v2)

scalar = 2
v_scaled = scalar*v1

dot_pro = np.dot(v1,v2)

magnitude_v1 = np.linalg.norm(v1)

print('Vector 1:', v1)
print('Vector 2:', v2)
print('Sum of vectors:',v_add,',', "Vector Subtraction", v_sub)
print('Vector v1 scaled:', v_scaled)
print('Dot Product:', dot_pro)
print('Magnitude of V1:', magnitude_v1)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Sum of vectors: [-3 -3 -3] , Vector Subtraction [5 7 9]
Vector v1 scaled: [2 4 6]
Dot Product: 32
Magnitude of V1: 3.7416573867739413


In [28]:
#Matrices

a =  np.array([[1,2,3], [4,5,6]])

b =  np.array([[7,8,9], [10,11,12], [13,14,15]])

c =  np.array([[1,2,3], [4,5,6]])

matrix_add = a + c 
matrix_subtract = a -c 

print("a+c = \n", matrix_add)
print("a-c = \n", matrix_subtract)

matrix_mul = np.dot(a, b)

print("Matrix Dot Product for every number in each row & column:\n", matrix_mul)

matrix_transpose = a.T
print("Transposed matrix of a:\n", matrix_transpose)

a+c = 
 [[ 2  4  6]
 [ 8 10 12]]
a-c = 
 [[0 0 0]
 [0 0 0]]
Matrix Dot Product for every number in each row & column:
 [[ 66  72  78]
 [156 171 186]]
Transposed matrix of a:
 [[1 4]
 [2 5]
 [3 6]]


In [34]:
#Solving for matrices
A = np.array([[2,3],[4,-1]])
print("Matrix one:\n", A)
B = np.array([5,3])
print("Matrix one:\n", B)
x = np.linalg.solve(A,B)
print("Matrices solved:\n", x)

Matrix one:
 [[ 2  3]
 [ 4 -1]]
Matrix one:
 [5 3]
Matrices solved:
 [1. 1.]


In [41]:
#Eigen vector and values

A = np.array([[2,1], [1,2]])
e_value, e_vectors = np.linalg.eig(A) #returns two values, thus you need two variables to call

print("eigen value:\n", e_value)
print("eigen vector:\n", e_vectors)

#Inverse of Matrices

A = np.array([[4,7], [2,6]])
Inverse_A = np.linalg.inv(A)
print("Inverse of the matrix A:\n", Inverse_A)
identity = np.dot(A, Inverse_A)
print("identity)


eigen value:
 [3. 1.]
eigen vector:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Inverse of the matrix A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
