In [11]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    
    L = np.eye(n) # Initialize L as an identity matrix
    
    U = np.array(A, dtype=float) # Copy of A to avoid modifying the original matrix
    
    for i in range(n): # Eliminate elements below the pivot (U[i, i])
        
        for j in range(i+1, n):
            if U[i, i] == 0:
                
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                
            factor = U[j, i] / U[i, i] # Multiplier for row operation
            
            L[j, i] = factor # Store multiplier in L
# Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    return L, U

# Example usage
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)


print("Original Matrix A: \n", L@U) #@ is the symbol for matrix multiplication

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]
Original Matrix A: 
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]


In [33]:
#Jacobi method

import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
# Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

# Example usage
A = np.array([[4, -1, 0, 0,5],
             [-1, 4, -1, 0,5],
             [0, -1, 4, -1,5]
             [0, 0, -1, 3,5]])

b = np.array([15, 10, 10, 10,-5])

x0 = np.zeros_like(b)

tol = 1e-6
max_iterations = 100

solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

<>:22: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:22: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-33-536906eaeba4>:22: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [0, -1, 4, -1,5]


TypeError: list indices must be integers or slices, not tuple

In [41]:
import numpy as np
import time

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
# Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
           return x_new, k
        x = x_new

    return x, max_iterations
#Example Usage
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]])

b = np.array([15, 10, 10, 10])

x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
start_time = time.perf_counter()
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
end_time = time.perf_counter()
elapsed_time = end_time - start_time
print("The elapsed time is:", elapsed_time, "seconds")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")


The elapsed time is: 0.0005617067217826843 seconds
Solution: [4 4 4 4]
Iterations: 2
